save:main.o  sauvegarde.o  EnigmesC.o 
	gcc main.o  sauvegarde.o   EnigmesC.o  -o save -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g
main.o:main.c
	gcc -c main.c  -g
sauvegarde.o :sauvegarder.c
	gcc -c sauvegarder.c  -g

EnigmesC.o:EnigmesC.c
        gcc -c EnigmesC.c -g
mainE.o: mainE.c
        gcc -c mainE.c -g
