save:main_Sauvegarder.o  Sauvegarder.o 
	gcc main_Sauvegarder.o  Sauvegarder.o   -o save -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer -g
main_Sauvegarder.o:main_Sauvegarder.c
	gcc -c main_Sauvegarder.c  -g
Sauvegarde.o :Sauvegarder.c
	gcc -c Sauvegarder.c  -g
